### ISSUE TITLE
Taking ages.. maybe my laptop settings are making progress slow..

### ISSUE THREAD

**Issue by davidhodge931** [davidhodge931/vape-scrape#7]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/09c4af97-7e18-4826-9967-741f46e184b4">

**Comment by davidhodge931** [comment]
Are you able to upload the completed dataset @skittogh ?

**Comment by skittogh** [comment]
wow 22 days !! somethings not right there. its slow, but shouldn't be that slow! I think the csv here should be the full run:
![image](https://github.com/user-attachments/assets/9eb5fa50-2213-43e7-a053-0de7f49db33a)
Also I have lost access to my teams chat since my laptop updated to windows 11, so no comms there

**Comment by skittogh** [comment]
also it shouldn't really push your laptop hard. Its not doing much, just slow because we dont want to ping the web server too often

**Comment by davidhodge931** [comment]
Is it possible to get the caffeine concentration as well as the flavour as per my initial attempt at scraping this data?

**Comment by skittogh** [comment]
this should all be bundled up into details column of the full dataset. Then can use some post processing on the output file to get these things (which hasn't been scripted yet). The rationale was that the class in which these specific details were stored was really inconsistent across pages, so grab all the details the we can, the later use str_subset() or similar to get specific flavour etc if it exists. Ill have a go at running the script later to see if its as slow here
